[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src *; style-src * 'unsafe-inline'; script-src * 'unsafe-inline' 'unsafe-eval'; img-src * data: blob:; font-src *;"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
